### ISSUE TITLE
Members page broken for non-admin

### ISSUE THREAD

**Issue by s6fsr6** [sbrajesh/buddypress-multi-network#8]
Hello,

I hope someone can help me here with an issue I face. For me (admin), members page displays correctly - all members are visible and all is working fine. However, for non-admin users, members page is broken (see attached screenshot). I have no idea what this might be caused by, but now I have paid members who don't actually see other members because of this error. I tried deactivating plugins, etc.

Thank you,

Martin

![non admins](https://user-images.githubusercontent.com/27063342/62878131-c69c8a00-bd28-11e9-9f27-12884a73d4cd.jpg)
![admin](https://user-images.githubusercontent.com/27063342/62878145-cb613e00-bd28-11e9-8f34-9b9387233088.jpg)

**Comment by sbrajesh** [comment]
Hi,
Are you using BuddyPress Multi Network plugin? We don't have any filter that will make things visible for admin and invisible for others.

We do filter user lists on sub sites to display site specific users. But that is always same whether a super admin sees it or some other.

I am guessing you are using some code or plugin to filter/hi/exclude some users and that is causing the issue.

**Comment by s6fsr6** [comment]
Hi sbrajesh,

Thank you very much for your comment. I just tried to deactivate plugin called 'BP Messaging Controll' and everything works fine now. I apologize for taking your time.

Martin

**Comment by sbrajesh** [comment]
Hi Martin,
No issues. I am glad it is resolved for you :)
